######################################################################
# Automatically generated by qmake (2.01a) Fri Jul 17 17:03:40 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mainwindow.h MyGraphicsItem.h
SOURCES += main.cpp mainwindow.cpp MyGraphicsItem.cpp