######################################################################
# Automatically generated by qmake (2.01a) Fri Jul 10 10:49:58 2015
######################################################################

TEMPLATE = app
QMAKE_CXXFLAGS += -std=c++11
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += main_window.h
SOURCES += main.cpp main_window.cpp
