######################################################################
# Automatically generated by qmake (2.01a) Tue Jul 14 11:05:09 2015
######################################################################

TEMPLATE = app
TARGET = 
QMAKE_CXXFLAGS += -std=c++11
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += Main_window.h \
           MyCanvas.h \

SOURCES += main.cpp \
           Main_window.cpp \
           MyCanvas.cpp \
