######################################################################
# Automatically generated by qmake (2.01a) Mon Jul 13 11:51:03 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += dialog.h
SOURCES += dialog.cpp main.cpp
