######################################################################
# Automatically generated by qmake (2.01a) Wed Feb 25 17:10:54 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
