######################################################################
# Automatically generated by qmake (2.01a) Wed Mar 11 17:28:38 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += main_window.h
SOURCES += main.cpp main_window.cpp
