######################################################################
# Automatically generated by qmake (2.01a) Wed Feb 25 17:25:01 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += profile_widget.h
SOURCES += main.cpp profile_widget.cpp
